# Generated by Django 4.0.5 on 2022-07-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='status',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Finalizado'), ('3', 'En proceso')], default='En proceso', max_length=50),
        ),
    ]
