# Generated by Django 4.0.5 on 2022-07-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_obra_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='notas',
            field=models.CharField(default='', max_length=800, null=True),
        ),
    ]
