# Generated by Django 4.0.5 on 2022-07-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_insumos_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='bodegaproductos',
            name='ubicacion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
