# Generated by Django 4.0.5 on 2022-07-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_producto_ubicacion_bodegaproductos_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='notas',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
    ]
