# Generated by Django 4.0.5 on 2022-07-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_insumos_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='unidad',
            field=models.CharField(default='', max_length=300),
        ),
    ]
