# Generated by Django 4.0.5 on 2022-07-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_solicitud_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodegaproductos',
            name='producto',
        ),
        migrations.AddField(
            model_name='bodegaproductos',
            name='categoria',
            field=models.CharField(choices=[('1', 'EQUIPO'), ('2', 'MUEBLE'), ('3', 'ACCESORIO'), ('4', 'HERRERIA'), ('5', 'CANCELERIA'), ('6', 'CARPINTERIA'), ('7', 'ACABADO'), ('8', 'MATERIAL')], default=0, max_length=80),
        ),
        migrations.AddField(
            model_name='bodegaproductos',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bodegaproductos',
            name='proveedor',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bodegaproductos',
            name='unidad',
            field=models.CharField(choices=[('1', 'PIEZA'), ('2', 'CUBETA'), ('3', 'GALON'), ('4', 'BULTO'), ('5', 'm3'), ('6', 'KG'), ('7', 'TONELADA'), ('8', 'MILLA'), ('9', 'LITRO'), ('10', 'JUEGO'), ('11', 'LOTE'), ('12', 'm2')], default=0, max_length=80),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
