# Generated by Django 4.0.5 on 2022-07-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_bodegaproductos_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodegaproductos',
            name='clave',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
