# Generated by Django 4.0.5 on 2022-07-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_bodegaproductos_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.CharField(max_length=3)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ruta', models.FileField(upload_to='media/xlm/')),
            ],
        ),
    ]
