# Generated by Django 4.0.5 on 2022-07-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='ruta',
            field=models.FileField(upload_to='media'),
        ),
    ]
